name: nextcloud
version: 3.0.2+1
description: A Nextcloud client for dart which can use several official Nextcloud APIs
homepage: https://github.com/jld3103/dart-nextcloud

environment:
  sdk: ^2.12.0

dependencies:
  http: ^0.13.5
  intl: ^0.18.0
  xml: ^6.2.2

dev_dependencies:
  mockito: ^5.4.0
  test: ^1.24.0
